INSERT INTO department (dep_name)
VALUES  ("Marketing"),
        ("Finance"),
        ("Tech"),
        ("Human Resources"),
        ("Retail"),
        ("Other");

INSERT INTO roles (title, salary, department_id)
VALUES  ("Social Media Rep", 62000, 1),
        ("Marketing Manager", 85000, 1),
        ("Sales Rep", 73000, 1),
        ("Advertising Consultant", 70000, 1),
        ("Marketing Intern", 50000, 1),
        ("Accountant", 80000, 2),
        ("Finance Manager", 100000, 2),
        ("Fundraiser", 80000, 2),
        ("Finance Intern", 50000, 2),
        ("Tech Engineer", 85000, 3),
        ("Tech Manager", 99000, 3),
        ("Tech Intern", 55000, 3),
        ("HR Rep", 75000, 4),
        ("Retailer", 55000, 5),
        ("Store Manager", 80000, 5),
        ("Stock Boy", 45000, 5),
        ("Executive Assistant", 90000, 6),
        ("CEO", 220000, 6);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ("Fred", "Weasley", 2, null),
        ("Ivan", "Karamazov", 1, 1),
        ("Eugene", "Henderson", 3, 1),
        ("Sancho", "Panza", 4, 1),
        ("Elinor", "Dashwood", 5, 1),
        ("Emma", "Woodhouse", 8, 13),
        ("Adam", "Trask", 10, 16),
        ("Seymour", "Levov", 6, 13),
        ("Ivan", "Denisovich", 5, 1),
        ("Caddy", "Compson", 8, 13),
        ("Stella", "Vignes", 9, 13),
        ("Starr", "Carter", 4, 1),
        ("Ignatius", "Reilly", 7, null),
        ("Liesel", "Meminger", 8, 13),
        ("Humbert", "Humbert", 9, 13),
        ("Adah", "Price", 11, null),
        ("Cuffy", "Lambkin", 12, 16),
        ("Pinky", "Madame", 13, null),
        ("Dene", "Oxendine", 18, null), 
        ("Thomas", "Sutpen", 17, 19),
        ("Addie", "Bundren", 16, 22),
        ("Anna", "Karenina", 15, null),
        ("Pierre", "Bezukhov", 14, 22),
        ("Tom", "Joad", 13, null),
        ("Rodion", "Raskolnikov", 17, 19),
        ("Antonia", "Shimerda", 16, 22),
        ("Claude", "Love", 16, 22),
        ("Elizabeth", "Bennet", 16, 22),
        ("Scout", "Finch", 14, 22),
        ("John", "Yossarian", 14, 22),
        ("John", "Grimes", 1, 1),
        ("Jane", "Eyre", 1, 1),
        ("Augie", "March", 6, 13),
        ("David", "Copperfield", 9, 13),
        ("Arya", "Stark", 9, 13),
        ("Daisy", "Miller", 12, 6);